name: guidegs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.8
  - pip
  - pytorch=2.1.2
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - tqdm
